### ISSUE TITLE
pdf to page-xml

### ISSUE THREAD

**Issue by ghost** [dariok/pdf2tei#1]
@dariok Thank you for your hard work,

Will you consider PDF2Page-xml.

**Comment by dariok** [comment]
@deepseek Sorry for the late answer. I have not yet planned it but will likely add sth. for that in a few weeks. Stay tuned (and maybe send a reminder).

**Comment by ghost** [comment]
@dariok Hi,
this is a reminder for considering `pdf2page-xml`
waiting for your reply
